[alice]
Q = {t = 2, m = [{n = "bob"}, {n = "carol"}]}

[bob]
Q = {t = 2, m = [{n = "alice"}, {n = "carol"}]}

[carol]
Q = {t = 2, m = [{n = "alice"}, {n = "bob"}]}

[dave]
Q = {t = 2, m = [{n = "bob"}, {n = "carol"}]}
